In [45]:
import numpy as np
n=5
np.random.seed(483)
a = np.random.randint(2, size=(n, n))
a


array([[0, 0, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 0, 0, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 1, 0, 1]])

In [46]:
b=[]
count=0
island=0
size=0
print(a)
#所有1的位置
for i in range(n):
    for j in range(n):
        if a[i,j]==1:
            b.append([j,i])
# print(b)


# 判斷
for c in b:
    #buffer歸零
    buffer=[0]
    
    #如果checked(2),就跳迴圈
    if a[c[1],c[0]]==2:
        continue
    
    #計算island數量
    print("=====")
    island+=1
    size=0
    print("第",island,"座島")
    
    #初步尋找矩陣值不為零的座標
    if c[0]+1!=n: #邊界條件
        if a[c[1],c[0]+1]==1: # x+1 位置判斷(往右一格)
            a[c[1],c[0]+1]=3
            buffer.append([c[0]+1,c[1]])
            count+=1
    if c[0]-1!=-1:
        if a[c[1],c[0]-1]==1: # x-1 位置判斷(往左一格)
            a[c[1],c[0]-1]=3
            buffer.append([c[0]-1,c[1]])
            count+=1
    if c[1]+1!=n:
        if a[c[1]+1,c[0]]==1: # y+1 位置判斷(往下一格)
            a[c[1]+1,c[0]]=3
            buffer.append([c[0],c[1]+1])
            count+=1
    if c[1]-1!=-1:
        if a[c[1]-1,c[0]]==1: # y-1 位置判斷(往上一格)
            a[c[1]-1,c[0]]=3
            buffer.append([c[0],c[1]-1])
            count+=1
    
    #將第一個不為零的矩陣位置改為checked並印出
    a[c[1],c[0]]=2
    print("初位置",[c[0],c[1]])
    size+=1
    
#     print(a) #目前狀況
#     print(buffer, count)
    
    #增加buffer格數並印出buffer
    for l in range(count,n+5):
        buffer.append([0,0])
#     print(buffer, count)

    #buffer功能
    while buffer[count]!=0:
        size+=1
        #目前判斷的位置
        print("目前位置: ",buffer[count])
        #偵測到1的數量
        add=0
        if buffer[count][0]+1!=n: #邊界條件
            if a[buffer[count][1],buffer[count][0]+1]==1: # x+1 位置判斷(往右一格)
                a[buffer[count][1],buffer[count][0]+1]=3 #將值命為pulled(3)
                add+=1
                buffer[count+add]=[buffer[count][0]+1,buffer[count][1]] #往buffer後一格放
                print("---判斷---增加: ",[buffer[count][0]+1,buffer[count][1]])
#                 print(buffer, count)
        if buffer[count][0]-1!=-1:
            if a[buffer[count][1],buffer[count][0]-1]==1: # x-1 位置判斷(往左一格)
                a[buffer[count][1],buffer[count][0]-1]=3
                add+=1
                buffer[count+add]=[buffer[count][0]-1,buffer[count][1]]
                print("---判斷---增加: ",[buffer[count][0]-1,buffer[count][1]])
#                 print(buffer, count)
        if buffer[count][1]+1!=n:
            if a[buffer[count][1]+1,buffer[count][0]]==1: # y+1 位置判斷(往下一格)
                a[buffer[count][1]+1,buffer[count][0]]=3
                add+=1
                buffer[count+add]=[buffer[count][0],buffer[count][1]+1]
                print("---判斷---增加: ",[buffer[count][0],buffer[count][1]+1])
#                 print(buffer, count)
        if buffer[count][1]-1!=-1:
            if a[buffer[count][1]-1,buffer[count][0]]==1: # y-1 位置判斷(往上一格)
                a[buffer[count][1]-1,buffer[count][0]]=3
                add+=1
                buffer[count+add]=[buffer[count][0],buffer[count][1]-1]
                print("---判斷---增加: ",[buffer[count][0],buffer[count][1]-1])
#                 print(buffer, count)
            
        a[buffer[count][1],buffer[count][0]]=2 #將目前的值令checked(2)
#         print("---移位---")
        for k in range(count,count+add+1): #將buffer座標全部往前移
            buffer[k]=buffer[k+1]
        count=count+add-1 #接下來要測的座標
    
#         print(buffer, count)
        print(a)
#         print("=====")

    if count==0:
        print("size=",size)
        
print("共",island,"座島")


[[0 0 1 1 1]
 [1 0 0 0 1]
 [1 1 0 0 0]
 [1 0 1 0 1]
 [0 1 1 0 1]]
=====
第 1 座島
初位置 [2, 0]
目前位置:  [3, 0]
---判斷---增加:  [4, 0]
[[0 0 2 2 3]
 [1 0 0 0 1]
 [1 1 0 0 0]
 [1 0 1 0 1]
 [0 1 1 0 1]]
目前位置:  [4, 0]
---判斷---增加:  [4, 1]
[[0 0 2 2 2]
 [1 0 0 0 3]
 [1 1 0 0 0]
 [1 0 1 0 1]
 [0 1 1 0 1]]
目前位置:  [4, 1]
[[0 0 2 2 2]
 [1 0 0 0 2]
 [1 1 0 0 0]
 [1 0 1 0 1]
 [0 1 1 0 1]]
size= 4
=====
第 2 座島
初位置 [0, 1]
目前位置:  [0, 2]
---判斷---增加:  [1, 2]
---判斷---增加:  [0, 3]
[[0 0 2 2 2]
 [2 0 0 0 2]
 [2 3 0 0 0]
 [3 0 1 0 1]
 [0 1 1 0 1]]
目前位置:  [0, 3]
[[0 0 2 2 2]
 [2 0 0 0 2]
 [2 3 0 0 0]
 [2 0 1 0 1]
 [0 1 1 0 1]]
目前位置:  [1, 2]
[[0 0 2 2 2]
 [2 0 0 0 2]
 [2 2 0 0 0]
 [2 0 1 0 1]
 [0 1 1 0 1]]
size= 4
=====
第 3 座島
初位置 [2, 3]
目前位置:  [2, 4]
---判斷---增加:  [1, 4]
[[0 0 2 2 2]
 [2 0 0 0 2]
 [2 2 0 0 0]
 [2 0 2 0 1]
 [0 3 2 0 1]]
目前位置:  [1, 4]
[[0 0 2 2 2]
 [2 0 0 0 2]
 [2 2 0 0 0]
 [2 0 2 0 1]
 [0 2 2 0 1]]
size= 3
=====
第 4 座島
初位置 [4, 3]
目前位置:  [4, 4]
[[0 0 2 2 2]
 [2 0 0 0 2]
 [2 2 0 0 0]
 [2 0 2 0 2]
 [0 2 2 