In [99]:
import numpy as np
n=12
np.random.seed(488)
a = np.random.randint(2, size=(n, n))
a


array([[1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1],
       [1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1],
       [1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0],
       [0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1],
       [1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1],
       [0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0],
       [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1],
       [1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0],
       [1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1]])

In [100]:
b=[]
count=0
island=0
print(a)
#所有1的位置
for i in range(n):
    for j in range(n):
        if a[i,j]==1:
            b.append([j,i])
print(b)


# 判斷
for c in b:
    #buffer歸零
    buffer=[0]
    
    #如果checked(2),就跳迴圈
    if a[c[1],c[0]]==2:
        continue
    
    #計算island數量
    print("=====")
    island+=1
    print("第",island,"座島")
    
    #初步尋找矩陣值不為零的座標
    if c[0]+1!=n: #邊界條件
        if a[c[1],c[0]+1]==1: # x+1 位置判斷(往右一格)
            a[c[1],c[0]+1]=3
            buffer.append([c[0]+1,c[1]])
            count+=1
    if c[0]-1!=-1:
        if a[c[1],c[0]-1]==1: # x-1 位置判斷(往左一格)
            a[c[1],c[0]-1]=3
            buffer.append([c[0]-1,c[1]])
            count+=1
    if c[1]+1!=n:
        if a[c[1]+1,c[0]]==1: # y+1 位置判斷(往下一格)
            a[c[1]+1,c[0]]=3
            buffer.append([c[0],c[1]+1])
            count+=1
    if c[1]-1!=-1:
        if a[c[1]-1,c[0]]==1: # y-1 位置判斷(往上一格)
            a[c[1]-1,c[0]]=3
            buffer.append([c[0],c[1]-1])
            count+=1
    
    #將第一個不為零的矩陣位置改為checked並印出
    a[c[1],c[0]]=2
    print(a) #目前狀況
    print(buffer, count)
    
    #增加buffer格數並印出buffer
    for l in range(count,n+5):
        buffer.append([0,0])
    print(buffer, count)

    #buffer功能
    while buffer[count]!=0:
        #目前判斷的位置
        print("位置: ",buffer[count])
        #偵測到1的數量
        add=0
        if buffer[count][0]+1!=n: #邊界條件
            if a[buffer[count][1],buffer[count][0]+1]==1: # x+1 位置判斷(往右一格)
                a[buffer[count][1],buffer[count][0]+1]=3 #將值命為pulled(3)
                add+=1
                buffer[count+add]=[buffer[count][0]+1,buffer[count][1]] #往buffer後一格放
                print("---判斷---增加: ",[buffer[count][0]+1,buffer[count][1]])
                print(buffer, count)
        if buffer[count][0]-1!=-1:
            if a[buffer[count][1],buffer[count][0]-1]==1: # x-1 位置判斷(往左一格)
                a[buffer[count][1],buffer[count][0]-1]=3
                add+=1
                buffer[count+add]=[buffer[count][0]-1,buffer[count][1]]
                print("---判斷---增加: ",[buffer[count][0]-1,buffer[count][1]])
                print(buffer, count)
        if buffer[count][1]+1!=n:
            if a[buffer[count][1]+1,buffer[count][0]]==1: # y+1 位置判斷(往下一格)
                a[buffer[count][1]+1,buffer[count][0]]=3
                add+=1
                buffer[count+add]=[buffer[count][0],buffer[count][1]+1]
                print("---判斷---增加: ",[buffer[count][0],buffer[count][1]+1])
                print(buffer, count)
        if buffer[count][1]-1!=-1:
            if a[buffer[count][1]-1,buffer[count][0]]==1: # y-1 位置判斷(往上一格)
                a[buffer[count][1]-1,buffer[count][0]]=3
                add+=1
                buffer[count+add]=[buffer[count][0],buffer[count][1]-1]
                print("---判斷---增加: ",[buffer[count][0],buffer[count][1]-1])
                print(buffer, count)
            
        a[buffer[count][1],buffer[count][0]]=2 #將目前的值令checked(2)
        print("---移位---")
        for k in range(count,count+add+1): #將buffer座標全部往前移
            buffer[k]=buffer[k+1]
        count=count+add-1 #接下來要測的座標
        print(buffer, count)
        print(a)
        print("=====")

print("共",island,"座島")


[[1 1 0 1 1 1 1 0 0 0 0 1]
 [1 0 0 1 0 1 0 0 0 1 0 1]
 [1 1 1 0 1 0 1 1 0 0 1 0]
 [0 0 1 1 1 1 1 1 0 0 0 0]
 [0 1 0 1 0 1 1 0 0 1 1 1]
 [1 0 1 1 0 1 1 1 1 1 0 1]
 [0 0 0 1 1 0 0 1 1 1 0 0]
 [1 1 0 1 0 0 1 0 1 1 0 1]
 [1 1 0 0 1 1 1 0 1 0 1 0]
 [1 0 0 1 0 1 0 0 0 0 0 1]
 [1 0 0 1 0 1 1 0 0 0 0 0]
 [1 0 1 0 0 1 0 1 0 0 1 1]]
[[0, 0], [1, 0], [3, 0], [4, 0], [5, 0], [6, 0], [11, 0], [0, 1], [3, 1], [5, 1], [9, 1], [11, 1], [0, 2], [1, 2], [2, 2], [4, 2], [6, 2], [7, 2], [10, 2], [2, 3], [3, 3], [4, 3], [5, 3], [6, 3], [7, 3], [1, 4], [3, 4], [5, 4], [6, 4], [9, 4], [10, 4], [11, 4], [0, 5], [2, 5], [3, 5], [5, 5], [6, 5], [7, 5], [8, 5], [9, 5], [11, 5], [3, 6], [4, 6], [7, 6], [8, 6], [9, 6], [0, 7], [1, 7], [3, 7], [6, 7], [8, 7], [9, 7], [11, 7], [0, 8], [1, 8], [4, 8], [5, 8], [6, 8], [8, 8], [10, 8], [0, 9], [3, 9], [5, 9], [11, 9], [0, 10], [3, 10], [5, 10], [6, 10], [0, 11], [2, 11], [5, 11], [7, 11], [10, 11], [11, 11]]
=====
第 1 座島
[[2 3 0 1 1 1 1 0 0 0 0 1]
 [3 0 0 1 0 1 0 0 0 1